export const KIWISAVER_SCHEMES = [
  { name: 'ANZ Default KiwiSaver Scheme', provider: 'ANZ', type: 'Conservative' },
  { name: 'ANZ KiwiSaver Balanced Growth', provider: 'ANZ', type: 'Balanced' },
  { name: 'ANZ KiwiSaver Growth', provider: 'ANZ', type: 'Growth' },
  { name: 'ANZ KiwiSaver High Growth Fund', provider: 'ANZ', type: 'Aggressive' },
  { name: 'ASB KiwiSaver Aggressive Fund', provider: 'ASB', type: 'Aggressive' },
  { name: 'ASB KiwiSaver Conservative', provider: 'ASB', type: 'Conservative' },
  { name: 'ASB KiwiSaver Moderate', provider: 'ASB', type: 'Balanced' },
  { name: 'ASB KiwiSaver Growth', provider: 'ASB', type: 'Growth' },
  { name: 'BNZ KiwiSaver Conservative', provider: 'BNZ', type: 'Conservative' },
  { name: 'BNZ KiwiSaver Balanced', provider: 'BNZ', type: 'Balanced' },
  { name: 'BNZ KiwiSaver Growth', provider: 'BNZ', type: 'Growth' },
  { name: 'Fisher Funds Two Preservation', provider: 'Fisher Funds', type: 'Conservative' },
  { name: 'Fisher Funds Growth', provider: 'Fisher Funds', type: 'Growth' },
  { name: 'Simplicity KiwiSaver Conservative', provider: 'Simplicity', type: 'Conservative' },
  { name: 'Simplicity KiwiSaver Balanced', provider: 'Simplicity', type: 'Balanced' },
  { name: 'Simplicity KiwiSaver Growth', provider: 'Simplicity', type: 'Growth' },
  { name: 'Westpac KiwiSaver Conservative', provider: 'Westpac', type: 'Conservative' },
  { name: 'Westpac KiwiSaver Balanced', provider: 'Westpac', type: 'Balanced' },
  { name: 'Westpac KiwiSaver Growth', provider: 'Westpac', type: 'Growth' },
  { name: 'Westpac KiwiSaver High Growth Fund', provider: 'Westpac', type: 'Aggressive' },
];
